"""Grafx-based mixing console.

Phase-1 foundation for the grafx-prune-compatible refactor. Wraps grafx
processors into the structure used by grafx-prune:

    stems → [per-track strip: eq, gain_panning, stereo_imager, comp,
             noisegate, delay, reverb]
           → scatter-sum to instrument-group buses
           → [per-group bus: same 7 processors]
           → sum to master out

The parameter dict is the SAME shape as `grafx-prune` produces per song,
so labels generated by grafx-prune's per-song optimizer load directly as
encoder supervision targets — no translation, no information loss.

Design notes:
- No `grafx.GRAFX` graph machinery — we have a fixed structure (track →
  group → master) and a simple forward pass over `nn.ModuleDict`s is
  cleaner than building a graph per song.
- Each processor is called once on the full batch (or batch × N flat).
  All processors accept batched input.
- `MultitapDelay` returns `(audio, info_dict)` — we discard the info.
- Every processor is wrapped in `_DryWetLogitWrap` (matches grafx-prune,
  which also wraps every processor in `DryWet`). The teacher optimizes
  a per-node soft-mask logit (`sigmoid(logit) = wet`), so our wrapper
  takes a `drywet_logit` scalar per instance and applies sigmoid
  internally before blending dry+wet. Training-side: the schema gains
  one `(1,)` param per processor instance and L_param learns the
  drywet target in well-behaved logit space (no dead-sigmoid risk that
  predicting in [0,1] directly would invite).
- No `GainStagingRegularization` wrapping yet — it's a training-side
  regularization, not a structural concern.
"""

from __future__ import annotations

from typing import Sequence

import torch
import torch.nn as nn
from grafx import processors as gp


# Order matters: this is the signal flow through the strip and the group bus.
# Must match grafx-prune's `base.yaml::processors` exactly — the teacher
# optimizes parameters AGAINST this chain order, so applying its labels
# through a different order silently breaks rendering (a comp set for
# pre-gain audio means something different when the same params see
# post-gain audio).
DEFAULT_PROCESSOR_ORDER = (
    "eq",            # ZeroPhaseFIREqualizer  — 1024-bin linear-phase FIR
    "compressor",    # Compressor             — feedforward dynamic range comp
    "noisegate",     # NoiseGate              — hard gate
    "stereo_imager", # SideGainImager         — mid/side: side gain
    "gain_panning",  # StereoGain             — per-channel L/R gain
    "delay",         # MultitapDelay          — 40-tap with per-tap FIR
    "reverb",        # STFTMaskedNoiseReverb  — filtered-noise reverb (mid/side)
)


def _make_processor(name: str, max_input_len: int) -> nn.Module:
    """Instantiate a single grafx processor, wrapped in `_DryWetLogitWrap`."""
    kwargs = {}
    # These wrap LTI convolutions that need a max input length up front.
    if name in {"compressor", "noisegate", "delay", "reverb"}:
        kwargs["max_input_len"] = max_input_len
    match name:
        case "eq":            inner = gp.ZeroPhaseFIREqualizer(**kwargs)
        case "gain_panning":  inner = gp.StereoGain(**kwargs)
        case "stereo_imager": inner = gp.SideGainImager(**kwargs)
        case "compressor":    inner = gp.Compressor(**kwargs)
        case "noisegate":     inner = gp.NoiseGate(**kwargs)
        case "delay":         inner = gp.MultitapDelay(**kwargs)
        case "reverb":        inner = gp.STFTMaskedNoiseReverb(**kwargs)
        case _: raise ValueError(f"unknown processor: {name}")
    return _DryWetLogitWrap(inner)


class _DryWetLogitWrap(nn.Module):
    """Linear blend of dry input + wet processor output, indexed by a LOGIT.

    Matches grafx-prune's `DryWet` numerically: `wet = sigmoid(logit)` then
    `output = wet * processed + (1 - wet) * input`. grafx-prune's wrapper
    takes a pre-sigmoid'd `drywet_weight` ∈ [0, 1] as a "common parameter"
    at render time, whereas we save+predict the raw logit and sigmoid
    inside the wrapper. Two reasons for the logit choice:

      1. The teacher's `solver.soft_mask` IS the logit — saving it raw
         avoids a sigmoid → student-Huber → asin-style inverse round-trip.
      2. The encoder's Linear head can output (-inf, inf) with well-
         behaved gradients; predicting in [0, 1] via an extra sigmoid
         risks dead-sigmoid mode collapse (see notes/RUNS.md v6.2-round14
         for an instance of that failure in a sibling head).

    Forward arg `drywet_logit` is `(leading, 1)`; the inner processor's
    parameters are passed through as **kwargs. The wrapped processor
    sees the raw input and produces its full wet output; the wrapper
    blends in the dry residual.
    """

    def __init__(self, processor: nn.Module):
        super().__init__()
        self.processor = processor

    def forward(
        self,
        x: torch.Tensor,
        drywet_logit: torch.Tensor,
        **processor_kwargs,
    ) -> torch.Tensor:
        y = self.processor(x, **processor_kwargs)
        if isinstance(y, tuple):
            # Some processors (MultitapDelay) return (audio, info). We
            # discard the info — it's diagnostic, not part of the signal.
            y = y[0]
        # drywet_logit: (leading, 1) → broadcast over (C, T) of x/y.
        wet = torch.sigmoid(drywet_logit).view(-1, 1, 1)
        return wet * y + (1.0 - wet) * x

    def parameter_size(self) -> dict[str, tuple[int, ...] | int]:
        """Exposes the inner processor's params plus our `drywet_logit: 1`.

        Order matters for human-readable schema iteration; we put
        `drywet_logit` last so existing-printer assumptions about
        "first key is the headline param" still hold.
        """
        return {**self.processor.parameter_size(), "drywet_logit": 1}


def _normalize_shape(shp) -> tuple[int, ...]:
    """grafx `parameter_size()` returns int or tuple per param. Normalize."""
    if isinstance(shp, int):
        return (shp,)
    return tuple(shp)


class GrafxMixingConsole(nn.Module):
    """Two-level mixing console: per-track strip → instrument-group bus → master sum.

    Strip and group both use the same 7-processor chain (matches `grafx-prune`).
    Parameters for both levels are passed as dicts at forward-time:

        strip_params[processor_name][param_name] : (B, N, *param_shape)
        group_params[processor_name][param_name] : (B, G, *param_shape)

    Output: (B, 2, T) master mix.
    """

    def __init__(
        self,
        sample_rate: int = 48_000,
        max_input_len: int = 131_072,
        processors_list: Sequence[str] = DEFAULT_PROCESSOR_ORDER,
    ):
        super().__init__()
        self.sample_rate = sample_rate
        self.max_input_len = max_input_len
        self.processors_list = tuple(processors_list)

        # One copy of each processor for the strip and another for the group bus.
        # They have separate `nn.Module` weights (which for these DSP processors
        # is mostly fixed buffers, but `nn.ModuleDict` makes attribute access
        # tidy and registers the modules properly).
        self.strip_processors = nn.ModuleDict({
            name: _make_processor(name, max_input_len) for name in self.processors_list
        })
        self.group_processors = nn.ModuleDict({
            name: _make_processor(name, max_input_len) for name in self.processors_list
        })

    @property
    def strip_param_shapes(self) -> dict[str, dict[str, tuple[int, ...]]]:
        """`{processor_name: {param_name: shape}}` for the per-track strip.

        Used to size the encoder's output heads and to validate input dicts
        at forward time.
        """
        return {
            name: {k: _normalize_shape(v) for k, v in proc.parameter_size().items()}
            for name, proc in self.strip_processors.items()
        }

    @property
    def group_param_shapes(self) -> dict[str, dict[str, tuple[int, ...]]]:
        """Same shape introspection for the group-bus processors."""
        return {
            name: {k: _normalize_shape(v) for k, v in proc.parameter_size().items()}
            for name, proc in self.group_processors.items()
        }

    @staticmethod
    def _run_chain(
        x: torch.Tensor,
        processors_dict: nn.ModuleDict,
        params_dict: dict[str, dict[str, torch.Tensor]],
        order: Sequence[str],
    ) -> torch.Tensor:
        """Apply each processor in `order` to `x` with the given params.

        `params_dict[proc][param_name]` is shaped (leading, *param_shape).
        `x` is shaped (leading, 2, T). The leading dim must match.
        """
        for name in order:
            proc = processors_dict[name]
            kwargs = params_dict[name]
            y = proc(x, **kwargs)
            # MultitapDelay (and possibly others later) returns (audio, info).
            if isinstance(y, tuple):
                y = y[0]
            x = y
        return x

    @staticmethod
    def _run_chain_capture(
        x: torch.Tensor,
        processors_dict: nn.ModuleDict,
        params_dict: dict[str, dict[str, torch.Tensor]],
        order: Sequence[str],
    ) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
        """Like `_run_chain` but also returns audio *after* each processor.

        Returned dict is keyed by processor name (one entry per item in `order`).
        Final returned tensor matches the last entry of the dict.
        """
        intermediates: dict[str, torch.Tensor] = {}
        for name in order:
            proc = processors_dict[name]
            kwargs = params_dict[name]
            y = proc(x, **kwargs)
            if isinstance(y, tuple):
                y = y[0]
            x = y
            intermediates[name] = x
        return x, intermediates

    def forward(
        self,
        stems: torch.Tensor,                 # (B, N, 2, T)
        strip_params: dict[str, dict[str, torch.Tensor]],   # per-processor, per-param: (B, N, *shape)
        group_params: dict[str, dict[str, torch.Tensor]],   # per-processor, per-param: (B, G, *shape)
        group_assignments: torch.Tensor,     # (B, N) long ∈ [0, G)
        track_mask: torch.Tensor | None = None,             # (B, N) bool
        n_groups: int | None = None,
    ) -> torch.Tensor:
        """Forward through strip → group → master sum.

        Returns: (B, 2, T) mixed stereo audio.
        """
        if stems.dim() != 4 or stems.shape[2] != 2:
            raise ValueError(f"expected (B, N, 2, T) stems; got {stems.shape}")
        B, N, C, T = stems.shape
        if group_assignments.shape != (B, N):
            raise ValueError(f"group_assignments must be (B={B}, N={N}); got {group_assignments.shape}")
        if n_groups is None:
            n_groups = int(group_assignments.max().item()) + 1

        # ---- Per-track strip ----
        # Flatten (B, N) into the processor batch dim. All params follow suit.
        x = stems.reshape(B * N, C, T)
        flat_strip = {
            proc_name: {
                k: v.reshape(B * N, *v.shape[2:])
                for k, v in pp.items()
            }
            for proc_name, pp in strip_params.items()
        }
        x = self._run_chain(x, self.strip_processors, flat_strip, self.processors_list)
        # Restore (B, N, 2, T)
        x = x.reshape(B, N, C, T)

        # Zero out masked tracks before summing into groups.
        if track_mask is not None:
            x = x * track_mask.to(x.dtype).view(B, N, 1, 1)

        # ---- Scatter-sum tracks into instrument groups ----
        # group_out[b, g] = sum over n where group_assignments[b, n] == g of x[b, n]
        idx = group_assignments.long().view(B, N, 1, 1).expand(B, N, C, T)
        group_out = torch.zeros(B, n_groups, C, T, device=x.device, dtype=x.dtype)
        group_out.scatter_add_(dim=1, index=idx, src=x)

        # ---- Per-group bus chain ----
        g = group_out.reshape(B * n_groups, C, T)
        flat_group = {
            proc_name: {
                k: v.reshape(B * n_groups, *v.shape[2:])
                for k, v in pp.items()
            }
            for proc_name, pp in group_params.items()
        }
        g = self._run_chain(g, self.group_processors, flat_group, self.processors_list)
        g = g.reshape(B, n_groups, C, T)

        # ---- Master sum (no master-bus processors yet; grafx-prune doesn't have any either) ----
        mix = g.sum(dim=1)  # (B, 2, T)
        return mix

    def forward_with_intermediates(
        self,
        stems: torch.Tensor,                 # (B, N, 2, T)
        strip_params: dict[str, dict[str, torch.Tensor]],
        group_params: dict[str, dict[str, torch.Tensor]],
        group_assignments: torch.Tensor,     # (B, N) long
        track_mask: torch.Tensor | None = None,             # (B, N) bool
        n_groups: int | None = None,
    ) -> tuple[torch.Tensor, dict[str, torch.Tensor], dict[str, torch.Tensor]]:
        """Mirror of `forward()` that also returns per-stage audio.

        Returns:
            mix:         (B, 2, T) — final master, identical to forward()
            strip_inter: {proc_name: (B, N, 2, T)} audio AFTER each strip processor
            group_inter: {proc_name: (B, n_groups, 2, T)} audio AFTER each group processor

        Compute cost is the same as `forward()` (same processors run, same
        backward graph). Marginal memory is the held intermediate tensors,
        which are ~`len(processors_list) * audio_bytes` per level — cheap.
        """
        if stems.dim() != 4 or stems.shape[2] != 2:
            raise ValueError(f"expected (B, N, 2, T) stems; got {stems.shape}")
        B, N, C, T = stems.shape
        if group_assignments.shape != (B, N):
            raise ValueError(f"group_assignments must be (B={B}, N={N}); got {group_assignments.shape}")
        if n_groups is None:
            n_groups = int(group_assignments.max().item()) + 1

        # ---- Per-track strip with intermediate capture ----
        x = stems.reshape(B * N, C, T)
        flat_strip = {
            proc_name: {
                k: v.reshape(B * N, *v.shape[2:])
                for k, v in pp.items()
            }
            for proc_name, pp in strip_params.items()
        }
        x, flat_strip_inter = self._run_chain_capture(
            x, self.strip_processors, flat_strip, self.processors_list,
        )
        # Reshape captured intermediates back to (B, N, C, T)
        strip_inter = {
            name: t.reshape(B, N, C, T) for name, t in flat_strip_inter.items()
        }
        x = x.reshape(B, N, C, T)

        if track_mask is not None:
            x = x * track_mask.to(x.dtype).view(B, N, 1, 1)

        # ---- Scatter-sum into groups ----
        idx = group_assignments.long().view(B, N, 1, 1).expand(B, N, C, T)
        group_out = torch.zeros(B, n_groups, C, T, device=x.device, dtype=x.dtype)
        group_out.scatter_add_(dim=1, index=idx, src=x)

        # ---- Per-group bus chain with intermediate capture ----
        g = group_out.reshape(B * n_groups, C, T)
        flat_group = {
            proc_name: {
                k: v.reshape(B * n_groups, *v.shape[2:])
                for k, v in pp.items()
            }
            for proc_name, pp in group_params.items()
        }
        g, flat_group_inter = self._run_chain_capture(
            g, self.group_processors, flat_group, self.processors_list,
        )
        group_inter = {
            name: t.reshape(B, n_groups, C, T) for name, t in flat_group_inter.items()
        }
        g = g.reshape(B, n_groups, C, T)

        mix = g.sum(dim=1)  # (B, 2, T)
        return mix, strip_inter, group_inter


__all__ = ["GrafxMixingConsole", "DEFAULT_PROCESSOR_ORDER"]
